name: build-and-publish-ubuntu-container
on:
  push
env:
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: docker login
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfiles/ubuntu/Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY_PREFIX }}${{ github.event.repository.name}}:${{ github.ref }}
