name: run-tests
on:
  workflow_run:
    workflows:
        - build-and-publish-ubuntu-container
    types:
      - completed
jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: ""
    steps:
      - name: checkout
        uses: actions/checkout@v4